USE test_DB

DROP TABLE MEMBER;
DROP TABLE BOARD;

create table MEMBER(
	MEMBER_NO INT IDENTITY(1,1) NOT NULL,
	ID VARCHAR(30) UNIQUE,
	MEMBER_NAME VARCHAR(30) NOT NULL,
	PWD VARCHAR(30) NOT NULL,
	TEL VARCHAR(30)

	CONSTRAINT MEMBER_PK PRIMARY KEY (ID)
);

INSERT INTO MEMBER(ID, MEMBER_NAME, PWD, TEL) VALUES('kevin', '케빈', '1234', '01029595027');
INSERT INTO MEMBER(ID, MEMBER_NAME, PWD, TEL) VALUES('HONG', '홍', '1234', '01011112222');
INSERT INTO MEMBER(ID, MEMBER_NAME, PWD, TEL) VALUES('CALL', '콜', '1234', '0103334443');
INSERT INTO MEMBER(ID, MEMBER_NAME, PWD, TEL) VALUES('YOUUU', '유', '1234', '01022344332');
INSERT INTO MEMBER(ID, MEMBER_NAME, PWD, TEL) VALUES('LUCK', '럭', '1234', '01029522347');


SELECT * FROM MEMBER;


create table BOARD(
	BOARD_NO INT IDENTITY(1,1) NOT NULL,
	ID VARCHAR(30),
	TITLE VARCHAR(30) NOT NULL,
	CONTENTS VARCHAR(255) NOT NULL,
	DELFLAG varchar(1) DEFAULT NULL,

	CONSTRAINT BOARD_FK FOREIGN KEY(ID) references MEMBER
);

SELECT * FROM BOARD;

INSERT INTO BOARD (ID, TITLE, CONTENTS) VALUES('kevin', '안녕하세요', '질문이 있습니다 얼마인가요?');
INSERT INTO BOARD (ID, TITLE, CONTENTS) VALUES('LUCK', '행복', '행운이 가득하시기를');
INSERT INTO BOARD (ID, TITLE, CONTENTS) VALUES('LUCK', '욕은 자제해주세요', '아시겠죠?');
INSERT INTO BOARD (ID, TITLE, CONTENTS) VALUES('CALL', '콜', '빠이');

COMMIT;