/*
 저장프로시저
 SQL Server에서 제공되는 프로그래밍 기능, 즉 쿼리문의 집합으로서, 어떠한 동작을 일괄처리흐는 용도로 사용한다.
*/



-- SP 생성 예제1 - 데이터베이스에 MEMEBER를 검색하는 프로시저
CREATE PROCEDURE SELECT_MEMBER
	@USERID VARCHAR(30)
AS
	SELECT * FROM MEMBER WHERE ID = @USERID;
GO

EXECUTE SELECT_MEMBER 'CALL';

-- SP 생성 예제2 - 데이터베이스에 USER가 작성한 게시글을 검색하는 프로시저

CREATE PROCEDURE SEARCH_BOARD
	@USERID VARCHAR(30)
AS
	SELECT * FROM BOARD WHERE ID = @USERID;
GO

EXECUTE SEARCH_BOARD 'KEVIN';

CREATE PROCEDURE JOIN_MEMBER
	@USERID VARCHAR(30),
	@PWD VARCHAR(30),
	@NAME VARCHAR(30)
AS
	DECLARE @ERR INT;
	INSERT INTO MEMBER (ID, PWD, MEMBER_NAME)
	VALUES(@USERID, @PWD, @NAME);

	SELECT @ERR = @@ERROR
	IF @ERR != 0
	BEGIN
		PRINT '####' + @USERID + ' 등록에 실패했습니다.'
	END;

	RETURN @ERR;
GO

EXECUTE JOIN_MEMBER 'POWER', '1234', '힘'

EXECUTE JOIN_MEMBER 'POWER', '1234', '힘'

SELECT * FROM MEMBER ORDER BY MEMBER_NO DESC;
